-- Mapping from old territory names to new corrected names
UPDATE municipios SET territorio = 'Acapulco - Centro - Norte - Tierra Caliente' WHERE territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE';
UPDATE municipios SET territorio = 'Acayucan' WHERE territorio = 'ACAYUCAN';
UPDATE municipios SET territorio = 'Balancan' WHERE territorio = 'BALANCAN';
UPDATE municipios SET territorio = 'Colima' WHERE territorio = 'COLIMA';
UPDATE municipios SET territorio = 'Comalcalco' WHERE territorio = 'COMALCALCO';
UPDATE municipios SET territorio = 'Cordoba' WHERE territorio = 'CORDOBA';
UPDATE municipios SET territorio = 'Costa Chica - Montana' WHERE territorio = 'COSTA CHICA MONTAÑA';
UPDATE municipios SET territorio = 'Costa Grande - Sierra' WHERE territorio = 'COSTA GRANDE SIERRA';
UPDATE municipios SET territorio = 'Durango / Zacatecas' WHERE territorio = 'DURANGO ZACATECAS';
UPDATE municipios SET territorio = 'Tlaxcala / Estado de Mexico' WHERE territorio = 'ESTADO DE MEXICO Y TLAXCA';
UPDATE municipios SET territorio = 'Hidalgo' WHERE territorio = 'HIDALGO';
UPDATE municipios SET territorio = 'Michoacan' WHERE territorio = 'MICHOACAN';
UPDATE municipios SET territorio = 'Morelos' WHERE territorio = 'MORELOS';
UPDATE municipios SET territorio = 'Nayarit / Jalisco' WHERE territorio = 'NAYARIT JALISCO';
UPDATE municipios SET territorio = 'Istmo' WHERE territorio = 'OAXACA ISTMO';
UPDATE municipios SET territorio = 'Mixteca' WHERE territorio = 'OAXACA MIXTECA';
UPDATE municipios SET territorio = 'Ocosingo' WHERE territorio = 'OCOSINGO';
UPDATE municipios SET territorio = 'Tzucacab / Opb' WHERE territorio = 'OTHON P. BLANCO';
UPDATE municipios SET territorio = 'Palenque' WHERE territorio = 'PALENQUE';
UPDATE municipios SET territorio = 'Papantla' WHERE territorio = 'PAPANTLA';
UPDATE municipios SET territorio = 'Pichucalco' WHERE territorio = 'PICHUCALCO';
UPDATE municipios SET territorio = 'Puebla' WHERE territorio = 'PUEBLA';
UPDATE municipios SET territorio = 'San Luis Potosi' WHERE territorio = 'SAN LUIS POTOSI';
UPDATE municipios SET territorio = 'Sinaloa' WHERE territorio = 'SINALOA';
UPDATE municipios SET territorio = 'Chihuahua / Sonora' WHERE territorio = 'SONORA CHIHUAHUA';
UPDATE municipios SET territorio = 'Tamaulipas' WHERE territorio = 'TAMAULIPAS';
UPDATE municipios SET territorio = 'Tantoyuca' WHERE territorio = 'TANTOYUCA';
UPDATE municipios SET territorio = 'Tapachula' WHERE territorio = 'TAPACHULA';
UPDATE municipios SET territorio = 'Teapa' WHERE territorio = 'TEAPA';
UPDATE municipios SET territorio = 'Xpujil' WHERE territorio = 'XPUJIL';
