ALTER TABLE municipios ADD COLUMN IF NOT EXISTS territorio VARCHAR(100);
UPDATE municipios SET territorio = 'XPUJIL' WHERE clave_mun = 4003;
UPDATE municipios SET territorio = 'XPUJIL' WHERE clave_mun = 4007;
UPDATE municipios SET territorio = 'XPUJIL' WHERE clave_mun = 4005;
UPDATE municipios SET territorio = 'XPUJIL' WHERE clave_mun = 4004;
UPDATE municipios SET territorio = 'XPUJIL' WHERE clave_mun = 4011;
UPDATE municipios SET territorio = 'XPUJIL' WHERE clave_mun = 4002;
UPDATE municipios SET territorio = 'XPUJIL' WHERE clave_mun = 4006;
UPDATE municipios SET territorio = 'XPUJIL' WHERE clave_mun = 4001;
UPDATE municipios SET territorio = 'XPUJIL' WHERE clave_mun = 4010;
UPDATE municipios SET territorio = 'XPUJIL' WHERE clave_mun = 4009;
UPDATE municipios SET territorio = 'XPUJIL' WHERE clave_mun = 4008;
UPDATE municipios SET territorio = 'COLIMA' WHERE clave_mun = 6006;
UPDATE municipios SET territorio = 'COLIMA' WHERE clave_mun = 6002;
UPDATE municipios SET territorio = 'COLIMA' WHERE clave_mun = 6005;
UPDATE municipios SET territorio = 'COLIMA' WHERE clave_mun = 6008;
UPDATE municipios SET territorio = 'COLIMA' WHERE clave_mun = 6001;
UPDATE municipios SET territorio = 'COLIMA' WHERE clave_mun = 6004;
UPDATE municipios SET territorio = 'COLIMA' WHERE clave_mun = 6010;
UPDATE municipios SET territorio = 'COLIMA' WHERE clave_mun = 6003;
UPDATE municipios SET territorio = 'COLIMA' WHERE clave_mun = 6007;
UPDATE municipios SET territorio = 'COLIMA' WHERE clave_mun = 6009;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7090;
UPDATE municipios SET territorio = 'OCOSINGO' WHERE clave_mun = 7020;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7021;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7079;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7103;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7102;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7074;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7057;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7054;
UPDATE municipios SET territorio = 'PALENQUE' WHERE clave_mun = 7076;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7081;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7063;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7051;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7070;
UPDATE municipios SET territorio = 'PALENQUE' WHERE clave_mun = 7050;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7053;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7080;
UPDATE municipios SET territorio = 'PALENQUE' WHERE clave_mun = 7065;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7062;
UPDATE municipios SET territorio = 'PALENQUE' WHERE clave_mun = 7077;
UPDATE municipios SET territorio = 'OCOSINGO' WHERE clave_mun = 7082;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7042;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7025;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7018;
UPDATE municipios SET territorio = 'OCOSINGO' WHERE clave_mun = 7052;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7084;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7089;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7068;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7048;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7105;
UPDATE municipios SET territorio = 'PALENQUE' WHERE clave_mun = 7100;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7045;
UPDATE municipios SET territorio = 'PALENQUE' WHERE clave_mun = 7114;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7091;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7073;
UPDATE municipios SET territorio = 'OCOSINGO' WHERE clave_mun = 7008;
UPDATE municipios SET territorio = 'OCOSINGO' WHERE clave_mun = 7031;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7043;
UPDATE municipios SET territorio = 'PALENQUE' WHERE clave_mun = 7116;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7060;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7040;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7039;
UPDATE municipios SET territorio = 'OCOSINGO' WHERE clave_mun = 7099;
UPDATE municipios SET territorio = 'PALENQUE' WHERE clave_mun = 7096;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7001;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7036;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7003;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7011;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7012;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7072;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7037;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7010;
UPDATE municipios SET territorio = 'OCOSINGO' WHERE clave_mun = 7004;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7005;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7035;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7032;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7013;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7069;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7092;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7015;
UPDATE municipios SET territorio = 'PALENQUE' WHERE clave_mun = 7016;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7006;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7033;
UPDATE municipios SET territorio = 'OCOSINGO' WHERE clave_mun = 7115;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7071;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7066;
UPDATE municipios SET territorio = 'OCOSINGO' WHERE clave_mun = 7059;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7061;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7088;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7087;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7124;
UPDATE municipios SET territorio = 'PICHUCALCO' WHERE clave_mun = 7067;
UPDATE municipios SET territorio = 'TAPACHULA' WHERE clave_mun = 7055;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8056;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8007;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8041;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8051;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8022;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8020;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8012;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8009;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8008;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8040;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8063;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8030;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8027;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8019;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8064;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8066;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8065;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8046;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8047;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8029;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 8049;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10006;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10009;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10010;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10029;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10031;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10011;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10038;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10030;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10023;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10025;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10032;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10027;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10015;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10035;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10028;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10017;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10001;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10005;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10037;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10033;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10014;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10026;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10019;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10034;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10016;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10018;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10020;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10002;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10039;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10003;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 10024;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12033;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12031;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12083;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12073;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12065;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12054;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12053;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12066;
UPDATE municipios SET territorio = 'COSTA GRANDE SIERRA' WHERE clave_mun = 12048;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12007;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12012;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12006;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12010;
UPDATE municipios SET territorio = 'COSTA GRANDE SIERRA' WHERE clave_mun = 12011;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12032;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12028;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12029;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12004;
UPDATE municipios SET territorio = 'COSTA GRANDE SIERRA' WHERE clave_mun = 12068;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12039;
UPDATE municipios SET territorio = 'COSTA GRANDE SIERRA' WHERE clave_mun = 12038;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12043;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12030;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12064;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12067;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12001;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12019;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12045;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12008;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12009;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12046;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12036;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12044;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12042;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12040;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12076;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12075;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12074;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12072;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12071;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12070;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12069;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12052;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12041;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12062;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12023;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12013;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12024;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12027;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12055;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12025;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12026;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12059;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12077;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12078;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12061;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12018;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12056;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12003;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12002;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12035;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12017;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12020;
UPDATE municipios SET territorio = 'COSTA GRANDE SIERRA' WHERE clave_mun = 12057;
UPDATE municipios SET territorio = 'COSTA GRANDE SIERRA' WHERE clave_mun = 12021;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12022;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12063;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12058;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12051;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12050;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12081;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12080;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12005;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12049;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12079;
UPDATE municipios SET territorio = 'ACAPULCO CENTRO NORTE TIERRA CALIENTE' WHERE clave_mun = 12034;
UPDATE municipios SET territorio = 'COSTA CHICA MONTAÑA' WHERE clave_mun = 12084;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13004;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13081;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13034;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13080;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13079;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13032;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13018;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13071;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13053;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13068;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13078;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13031;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13025;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13026;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13027;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13028;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13043;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13014;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13015;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13046;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13062;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13073;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13060;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13011;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13042;
UPDATE municipios SET territorio = 'HIDALGO' WHERE clave_mun = 13084;
UPDATE municipios SET territorio = 'NAYARIT JALISCO' WHERE clave_mun = 14019;
UPDATE municipios SET territorio = 'NAYARIT JALISCO' WHERE clave_mun = 14061;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 15011;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 15002;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 15030;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 15028;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 15100;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 15069;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 15065;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 15099;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 15092;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 15093;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16090;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16006;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16008;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16009;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16096;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16097;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16107;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16010;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16032;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16077;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16001;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16013;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16021;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16087;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16022;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16079;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16075;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16033;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16035;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16038;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16039;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16049;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16053;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16014;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16016;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16082;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16056;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16080;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16057;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16059;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16064;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16065;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16055;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16029;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16026;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16025;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16024;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16066;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16073;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16091;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16092;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16111;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16101;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16100;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16084;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16102;
UPDATE municipios SET territorio = 'MICHOACAN' WHERE clave_mun = 16048;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17002;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17006;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17028;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17022;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17016;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17003;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17035;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17025;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17001;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17034;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17027;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17030;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17026;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17031;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17021;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17019;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17017;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17015;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17013;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17010;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17018;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17029;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17012;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17024;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17005;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17004;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17014;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17032;
UPDATE municipios SET territorio = 'MORELOS' WHERE clave_mun = 17033;
UPDATE municipios SET territorio = 'NAYARIT JALISCO' WHERE clave_mun = 18001;
UPDATE municipios SET territorio = 'NAYARIT JALISCO' WHERE clave_mun = 18009;
UPDATE municipios SET territorio = 'NAYARIT JALISCO' WHERE clave_mun = 18010;
UPDATE municipios SET territorio = 'NAYARIT JALISCO' WHERE clave_mun = 18011;
UPDATE municipios SET territorio = 'NAYARIT JALISCO' WHERE clave_mun = 18019;
UPDATE municipios SET territorio = 'NAYARIT JALISCO' WHERE clave_mun = 18005;
UPDATE municipios SET territorio = 'NAYARIT JALISCO' WHERE clave_mun = 18007;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20125;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20481;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20517;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20054;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20542;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20237;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20489;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20333;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20562;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20133;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20138;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20149;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20161;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20437;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20441;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20446;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20447;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20469;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20511;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20513;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20457;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20506;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20482;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20508;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20329;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20246;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20277;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20547;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20170;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20230;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20185;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20404;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20407;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20220;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20261;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20552;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20262;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20266;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20275;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20551;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20357;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20265;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20493;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20327;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20556;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20018;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20036;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20377;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20451;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20005;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20558;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20563;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20549;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20564;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20491;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20031;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20367;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20500;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20379;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20499;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20059;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20177;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20569;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20057;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20423;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20112;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20510;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20371;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20410;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20422;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20450;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20075;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20505;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20492;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20534;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20537;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20548;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20463;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20467;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20514;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20118;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20518;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20440;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20521;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20256;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20003;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20030;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20017;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20520;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20019;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20024;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20025;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20026;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20515;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20516;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20050;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20035;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20051;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20536;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20047;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20037;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20042;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20053;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20046;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20523;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20522;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20456;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20060;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20061;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20065;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20069;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20070;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20071;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20096;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20097;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20076;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20190;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20081;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20094;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20080;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20082;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20086;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20090;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20100;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20233;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20105;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20108;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20110;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20111;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20527;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20114;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20172;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20413;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20119;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20121;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20014;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20015;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20122;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20528;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20124;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20129;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20126;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20127;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20128;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20529;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20131;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20130;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20137;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20140;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20141;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20143;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20144;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20146;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20147;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20151;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20248;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20162;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20164;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20176;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20167;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20188;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20173;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20191;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20196;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20204;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20181;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20480;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20464;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20195;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20201;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20203;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20210;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20208;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20566;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20215;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20218;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20216;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20217;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20221;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20222;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20223;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20541;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20498;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20224;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20225;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20016;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20229;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20235;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20239;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20240;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20242;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20525;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20269;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20250;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20255;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20252;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20257;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20258;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20268;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20276;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20281;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20274;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20532;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20280;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20533;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20282;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20052;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20283;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20535;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20286;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20285;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20288;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20289;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20043;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20538;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20297;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20304;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20299;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20300;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20308;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20311;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20302;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20303;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20305;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20332;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20307;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20312;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20313;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20079;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20331;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20316;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20207;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20317;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20320;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20325;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20326;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20328;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20335;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20339;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20341;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20345;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20346;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20212;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20348;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20540;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20352;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20353;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20355;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20362;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20370;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20372;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20382;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20383;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20384;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20386;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20408;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20418;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20392;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20394;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20395;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20397;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20154;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20155;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20156;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20419;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20405;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20264;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20106;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20198;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20365;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20006;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20008;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20010;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20412;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20414;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20415;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20287;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20416;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20420;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20421;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20324;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20337;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20351;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20425;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20427;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20428;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20432;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20429;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20430;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20270;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20436;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20444;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20445;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20448;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20449;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20453;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20454;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20461;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20465;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20466;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20470;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20471;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20472;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20473;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20475;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20478;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20479;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20012;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20028;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20064;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20066;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20073;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20085;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20088;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20486;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20093;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20488;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20509;
UPDATE municipios SET territorio = 'OAXACA ISTMO' WHERE clave_mun = 20557;
UPDATE municipios SET territorio = 'OAXACA MIXTECA' WHERE clave_mun = 20038;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21180;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21080;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21088;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21083;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21197;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21193;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21192;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21215;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21216;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21199;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21178;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21105;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21132;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21143;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21174;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21102;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21101;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21100;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21099;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21001;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21109;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21204;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21108;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21167;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21181;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21064;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21148;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21063;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21207;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21057;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21107;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21200;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21095;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21094;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21091;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21208;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21030;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21029;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21028;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21077;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21074;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21022;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21025;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21177;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21075;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21078;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21079;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21187;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21188;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21194;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21184;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21104;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21122;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21123;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21054;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21213;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21159;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21154;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21172;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21153;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21121;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21202;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21203;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21073;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21044;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21060;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21068;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21072;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21161;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21186;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21170;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21117;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21017;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21019;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21173;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21175;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21069;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21162;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21126;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21128;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21158;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21053;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21002;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21004;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21005;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21006;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21008;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21134;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21138;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21205;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21023;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21115;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21114;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21146;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21150;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21014;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21015;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21016;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21026;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21165;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21211;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21212;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21163;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21049;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21048;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21164;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21210;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21043;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21084;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21086;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21131;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21089;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21040;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21039;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21076;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21183;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21071;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21070;
UPDATE municipios SET territorio = 'PUEBLA' WHERE clave_mun = 21111;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 23002;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 23004;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 23010;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 23007;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 23006;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 23009;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24050;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24053;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24054;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24013;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24042;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24012;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24041;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24040;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24039;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24038;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24037;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24036;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24031;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24029;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24026;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24023;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24022;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24021;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24016;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24014;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24001;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24057;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24034;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24003;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24046;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24018;
UPDATE municipios SET territorio = 'SAN LUIS POTOSI' WHERE clave_mun = 24019;
UPDATE municipios SET territorio = 'SINALOA' WHERE clave_mun = 25010;
UPDATE municipios SET territorio = 'SINALOA' WHERE clave_mun = 25003;
UPDATE municipios SET territorio = 'SINALOA' WHERE clave_mun = 25014;
UPDATE municipios SET territorio = 'SINALOA' WHERE clave_mun = 25001;
UPDATE municipios SET territorio = 'SINALOA' WHERE clave_mun = 25020;
UPDATE municipios SET territorio = 'SINALOA' WHERE clave_mun = 25019;
UPDATE municipios SET territorio = 'SINALOA' WHERE clave_mun = 25004;
UPDATE municipios SET territorio = 'SINALOA' WHERE clave_mun = 25005;
UPDATE municipios SET territorio = 'SINALOA' WHERE clave_mun = 25007;
UPDATE municipios SET territorio = 'SINALOA' WHERE clave_mun = 25013;
UPDATE municipios SET territorio = 'SINALOA' WHERE clave_mun = 25006;
UPDATE municipios SET territorio = 'SINALOA' WHERE clave_mun = 25017;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26066;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26038;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26033;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26031;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26062;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26052;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26051;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26037;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26021;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26015;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26069;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26009;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26024;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26003;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26005;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26068;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26049;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26063;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26012;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26044;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26010;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26072;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26061;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26018;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26042;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26008;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26040;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26067;
UPDATE municipios SET territorio = 'SONORA CHIHUAHUA' WHERE clave_mun = 26054;
UPDATE municipios SET territorio = 'COMALCALCO' WHERE clave_mun = 27006;
UPDATE municipios SET territorio = 'BALANCAN' WHERE clave_mun = 27001;
UPDATE municipios SET territorio = 'TEAPA' WHERE clave_mun = 27016;
UPDATE municipios SET territorio = 'TEAPA' WHERE clave_mun = 27015;
UPDATE municipios SET territorio = 'COMALCALCO' WHERE clave_mun = 27014;
UPDATE municipios SET territorio = 'TEAPA' WHERE clave_mun = 27012;
UPDATE municipios SET territorio = 'COMALCALCO' WHERE clave_mun = 27002;
UPDATE municipios SET territorio = 'COMALCALCO' WHERE clave_mun = 27003;
UPDATE municipios SET territorio = 'TEAPA' WHERE clave_mun = 27004;
UPDATE municipios SET territorio = 'COMALCALCO' WHERE clave_mun = 27005;
UPDATE municipios SET territorio = 'BALANCAN' WHERE clave_mun = 27007;
UPDATE municipios SET territorio = 'COMALCALCO' WHERE clave_mun = 27008;
UPDATE municipios SET territorio = 'TEAPA' WHERE clave_mun = 27009;
UPDATE municipios SET territorio = 'COMALCALCO' WHERE clave_mun = 27010;
UPDATE municipios SET territorio = 'BALANCAN' WHERE clave_mun = 27011;
UPDATE municipios SET territorio = 'COMALCALCO' WHERE clave_mun = 27013;
UPDATE municipios SET territorio = 'BALANCAN' WHERE clave_mun = 27017;
UPDATE municipios SET territorio = 'TAMAULIPAS' WHERE clave_mun = 28003;
UPDATE municipios SET territorio = 'TAMAULIPAS' WHERE clave_mun = 28041;
UPDATE municipios SET territorio = 'TAMAULIPAS' WHERE clave_mun = 28039;
UPDATE municipios SET territorio = 'TAMAULIPAS' WHERE clave_mun = 28037;
UPDATE municipios SET territorio = 'TAMAULIPAS' WHERE clave_mun = 28034;
UPDATE municipios SET territorio = 'TAMAULIPAS' WHERE clave_mun = 28036;
UPDATE municipios SET territorio = 'TAMAULIPAS' WHERE clave_mun = 28012;
UPDATE municipios SET territorio = 'TAMAULIPAS' WHERE clave_mun = 28013;
UPDATE municipios SET territorio = 'TAMAULIPAS' WHERE clave_mun = 28006;
UPDATE municipios SET territorio = 'TAMAULIPAS' WHERE clave_mun = 28019;
UPDATE municipios SET territorio = 'TAMAULIPAS' WHERE clave_mun = 28017;
UPDATE municipios SET territorio = 'TAMAULIPAS' WHERE clave_mun = 28008;
UPDATE municipios SET territorio = 'TAMAULIPAS' WHERE clave_mun = 28026;
UPDATE municipios SET territorio = 'TAMAULIPAS' WHERE clave_mun = 28002;
UPDATE municipios SET territorio = 'TAMAULIPAS' WHERE clave_mun = 28018;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29047;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29004;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29008;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29046;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29025;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29014;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29028;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29040;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29015;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29017;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29016;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29013;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29018;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29003;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29010;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29021;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29012;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29034;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29035;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29030;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29050;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29052;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29037;
UPDATE municipios SET territorio = 'ESTADO DE MEXICO Y TLAXCA' WHERE clave_mun = 29039;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30162;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30169;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30185;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30188;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30189;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30190;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30078;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30192;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30194;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30031;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30195;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30199;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30206;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30210;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30211;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30212;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30103;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30141;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30140;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30138;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30131;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30116;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30109;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30203;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30205;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30071;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30069;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30098;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30075;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30074;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30073;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30072;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30149;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30150;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30148;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30147;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30146;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30145;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30070;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30068;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30067;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30066;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30064;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30173;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30209;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30032;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30040;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30039;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30037;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30035;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30034;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30033;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30030;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30029;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30027;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30023;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30022;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30168;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30165;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30126;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30050;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30021;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30128;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30020;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30101;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30018;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30009;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30008;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30007;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30006;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30111;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30110;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30005;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30051;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30045;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30013;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30014;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30001;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30003;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30120;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30127;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30048;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30059;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30100;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30010;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30108;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30012;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30117;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30113;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30114;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30115;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30163;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30019;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30042;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30043;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30044;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30047;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30049;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30052;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30099;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30184;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30175;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30178;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30180;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30137;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30196;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30197;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30198;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30186;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30200;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30202;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30204;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30207;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30208;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30201;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30181;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30076;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30077;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30080;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30081;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30082;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30083;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30084;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30085;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30086;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30089;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30090;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30091;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30041;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30053;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30054;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30055;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30056;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30058;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30060;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30061;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30062;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30063;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30094;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30095;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30104;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30118;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30119;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30121;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30123;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30124;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30125;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30129;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30130;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30122;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30132;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30133;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30134;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30135;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30106;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30102;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30170;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30171;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30172;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30174;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30176;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30179;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30177;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30193;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30143;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30144;
UPDATE municipios SET territorio = 'ACAYUCAN' WHERE clave_mun = 30142;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30151;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30152;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30153;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30154;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30155;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30157;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30158;
UPDATE municipios SET territorio = 'CORDOBA' WHERE clave_mun = 30159;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30160;
UPDATE municipios SET territorio = 'TANTOYUCA' WHERE clave_mun = 30161;
UPDATE municipios SET territorio = 'PAPANTLA' WHERE clave_mun = 30167;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31009;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31007;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31019;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31101;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31106;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31105;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31103;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31097;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31081;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31088;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31066;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31086;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31082;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31080;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31102;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31071;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31069;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31078;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31037;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31027;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31058;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31055;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31036;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31032;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31077;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31074;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31026;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31025;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31001;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31023;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31035;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31034;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31016;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31015;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31049;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31065;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31064;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31073;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31072;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31093;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31014;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31089;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31070;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31068;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31012;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31010;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31002;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31060;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31054;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31053;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31076;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31098;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31042;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31052;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31006;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31056;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31057;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31062;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31040;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31085;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31104;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31091;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31048;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31096;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31099;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31005;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31047;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31046;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31045;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31043;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31067;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31075;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31004;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31003;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31022;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31033;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31079;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31094;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31084;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31029;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31038;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31030;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31021;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31092;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31018;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31017;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31024;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31031;
UPDATE municipios SET territorio = 'OTHON P. BLANCO' WHERE clave_mun = 31008;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 32040;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 32049;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 32042;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 32009;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 32022;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 32029;
UPDATE municipios SET territorio = 'DURANGO ZACATECAS' WHERE clave_mun = 32021;